Biling 21.04.2023/Biling/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('organisation.urls')),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Biling 21.04.2023/organisation/urls.py
from django.urls import path
# from .views import OrganisationView,LoginView,index,CustomerView,CustomerFormView,delete,edit,update,logout,invoicePage,InvoiceView
from .views import *

urlpatterns = [
    path('signup/',OrganisationView,name = 'signup'),
    path('',LoginView, name='login'),
    
    # Forget Password -----------
    
    path('forgotpass/',forgot_pass,name = 'forgotpass'),
    path('otpcheck/',otpcheck, name = 'otpcheck'),
    path('newpassword/',newpassword, name = 'newpassword'),
    
    # Forget Password -----------
    
    path('index/',index, name = 'index'),
    path('customer/',CustomerView,name = 'customer'),
    path('customerform/',CustomerFormView,name = 'customerform'),
    path('customerDelete/<int:cust_del>/',CustomerDelete,name='CustDel'),
    path('customerUpdate/<int:cust_up>/',CustomerUpdate,name='CustUp'),
    path('invoiceview/',InvoiceView,name = 'invoiceview'),
    path('invoicepage/<int:id>/',InvoicePage,name='invopage'),
    path('invoiceform/',InvoiceForm,name='invoiceform'),
    path('invoiceDelete/<int:invo_del>/',InvoiceDelete,name='InvoDel'),
    path('invoiceUpdate/<int:invo_up>/',InvoiceUpdate,name='InvoUp'),
    path('productview/',ProductView,name = 'productview'),
    path('productform/',ProductForm,name='productform'),
    path('addProductForm/',addProductForm,name='addProductForm'),
    path('updateaddProductForm/<int:id>',updateaddProductForm,name='updateaddProductForm'),
    path('viewquentity/',viewquentity,name='viewquentity'),
    path('productDelete/<int:prod_del>/',ProductDelete,name='ProdDel'),
    path('productUpdate/<int:prod_up>/',ProductUpdate,name='ProdUp'),
    path('detailpage/<int:id>',DetailPage,name='detailpage'),
    path('logout/',logout,name = "logout"),
    path('all_invoices/',Total_Invoice_Page,name='total_invoice_page'),
    
    # HTml To PDF -------------
    path('Generatedpdf/<int:id>',GeneratePdf,name="pdf"),
    
    # QRCode -------------
    path('QRCode_Generate/<int:id>/',QRCode_Generate,name='qrcode'),
    
    # Email --------
    path('SendMail/<int:id>',EmailCall,name='email'),
]

Biling 21.04.2023/organisation/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser

# from django.contrib.auth.models import User

class OrganisationDetails(models.Model):
    company_name = models.CharField(max_length=50)
    company_type = models.CharField(max_length=50)
    pan_number = models.CharField(max_length=10)
    gstin_number = models.CharField(max_length=15)
    address_1 = models.CharField(max_length=90)
    address_2 = models.CharField(max_length=90)
    state = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    pincode = models.CharField(max_length=6)
    full_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    email  = models.EmailField()
    user_id = models.CharField(max_length=40)
    password_1 = models.CharField(max_length=40)
    password_2 = models.CharField(max_length=40)

    def __str__(self):
        
        return self.company_name    

class CustomerDetails(models.Model):
    companyName = models.ForeignKey(OrganisationDetails, on_delete=models.CASCADE,default="")
    cust_name = models.CharField(max_length=50,verbose_name='Customer Name')
    cont_person = models.CharField(max_length=50,verbose_name='Contact Person')
    contact_num = models.IntegerField(verbose_name='Contact Number')
    email = models.CharField(max_length=50,default="")
    company_type = models.CharField(verbose_name='Company Type',max_length = 50)
    address = models.CharField(max_length=90,verbose_name='Address Line 1')
    address_2 = models.CharField(max_length=90,verbose_name='Address Line 2')
    landmark = models.CharField(max_length=50,verbose_name='Landmark')
    country = models.CharField(max_length=50,verbose_name='Country')
    state = models.CharField(max_length=50,verbose_name='State')
    city = models.CharField(max_length=50,verbose_name='City')
    pincode = models.IntegerField(verbose_name='Pincode')

    def __str__(self):
        return self.cust_name  


#--------------------------Invoice Page------------------->

#============= Model 1 - Invoice Details ===================>

class Invoice_Details(models.Model):
    companyName = models.ForeignKey(OrganisationDetails, on_delete=models.CASCADE,default="")
    Cust_name = models.ForeignKey(CustomerDetails, on_delete=models.CASCADE,default="")
    Invoice_type = models.CharField(max_length = 50)
    Invoice_num = models.CharField(max_length = 10)
    Date = models.DateField(auto_now=False,blank=True)
    Dispatch_through = models.CharField(max_length = 50)
    Due_date = models.DateField(auto_now=False,blank=True)
    Bank = models.CharField(max_length = 20)
    Payment_type = models.CharField(max_length = 20)
    Payment_note = models.TextField(max_length=50)
    T_c = models.TextField(max_length=100)
    Document_note = models.TextField(max_length=100)
    qrcode = models.ImageField(upload_to="", default="", blank=True)
    
    def __str__(self):
        return self.Invoice_num

#===========================================================>

#============== Model 2 - Product Details ==================>
class Product(models.Model):
    companyName = models.ForeignKey(OrganisationDetails, on_delete=models.CASCADE,default="")
    Invoice = models.ForeignKey(Invoice_Details, on_delete=models.CASCADE,default="")
    Product_name = models.CharField(max_length = 50)
    Hsn_code = models.CharField(max_length = 20)
    Qty = models.IntegerField()
    Price = models.IntegerField()
    Discount = models.IntegerField()
    Cgst = models.IntegerField()
    Sgst = models.IntegerField()
    Igst = models.IntegerField()
    Cess = models.IntegerField()
    Total = models.FloatField()
    
    def __str__(self):
        return self.Product_name
#----------------------------------------------------------
class AddProduct(models.Model):
    companyName = models.ForeignKey(OrganisationDetails, on_delete=models.CASCADE,default="")
    Product_name = models.CharField(max_length = 50)
    Qty = models.IntegerField()
    
    def __str__(self):
        return self.Product_name    

Biling 21.04.2023/organisation/forms.py
from django import forms
from .models import OrganisationDetails,CustomerDetails,Invoice_Details,Product
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

class CustomerForm(forms.ModelForm):
    class Meta:
        model = CustomerDetails
        fields = '__all__'


class OrganisationForm(forms.ModelForm):
    class Meta:
        model = OrganisationDetails
        fields = '__all__'

#============== Form 1 - Invoice Details ============>

class Invoice_Details_Form(forms.ModelForm):

    class Meta:
        model = Invoice_Details
        fields = '__all__'

#============== Form 2 - Product Details ============>

class Product_Form(forms.ModelForm):

    class Meta:
        model = Product
        exclude = ['']

Biling 21.04.2023/organisation/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import OrganisationDetails,CustomerDetails,Invoice_Details,Product,AddProduct
from .forms import OrganisationForm,CustomerForm,Invoice_Details_Form,Product_Form
from django.urls import reverse_lazy
from django.http import HttpResponse

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

from django.contrib import messages

# Forget PAssword -------
import random

# QRCode
import qrcode
from django.conf import settings # new

#email --------- 
import smtplib
import email.message
from smtplib import SMTP 


# Html To Pdf -------------------

from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template

from xhtml2pdf import pisa

from django.http import HttpResponse

# Html To Pdf -------------------

def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

def GeneratePdf(request,id):
    if 'org' in request.session:
        org = OrganisationDetails.objects.get(user_id = request.session['org'])
        invo = Invoice_Details.objects.get(id=id)
        prod = Product.objects.filter(Invoice=invo)
        cust_data = CustomerDetails.objects.get(cust_name=invo.Cust_name)
        tot = 0
        for i in prod:
            tot += float(i.Total)
        data = {'org':org,'cust':cust_data,'invo':invo,'prod':prod,'tot':tot}
        pdf = render_to_pdf('GeneratePdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')
    else:
        return redirect('login')

# QRCode -------------------------
def QRCode_Generate(request,id):
    if 'org' in request.session:
        org = OrganisationDetails.objects.get(user_id = request.session['org'])
        invo = Invoice_Details.objects.get(id=id)
        prod_no = Product.objects.filter(Invoice=invo).count()
        prod = Product.objects.filter(Invoice=invo)
        cust_data = CustomerDetails.objects.get(cust_name=invo.Cust_name)
        tot = 0
        for i in prod:
            tot += float(i.Total)
        # data = {'org':org,'cust':cust_data,'invo':invo,'prod':prod,'tot':tot}
        
        first = f"""
            Company Name : {org.company_name}
            Customer Name : {cust_data.cust_name}
            Invoice No. : {invo.Invoice_num}
            Total Products : {prod_no}
        """
        sec = ""
        for pr in prod:
            sec += """
            Product Name : """ + str(pr.Product_name) + """
            Product Qty : """ + str(pr.Qty) + """
            Product Price : """ + str(pr.Price) + """
            Product Total : """ + str(pr.Total) + "\n"
             
        third = f"""
            Total Amount To Pay : {tot}
        """
        
        data = first + sec + third
        
        qr = qrcode.QRCode(version=1,
                   error_correction=qrcode.constants.ERROR_CORRECT_L,
                   box_size=10,border=4,)
        qr.add_data(data)
        qr.make(fit=True)

        img = qr.make_image(fill_color="black", back_color="white")
        
        qrcode_nm = str(invo.Invoice_num)+".jpg"
        qrcode_path = settings.MEDIA_ROOT+"/"+qrcode_nm
        print(qrcode_path)
        img.save(qrcode_path)
        
        invo.qrcode = qrcode_nm
        invo.save()
        
        return render(request,'View_QRCode.html',{'org':org,'cust':cust_data,'invo':invo,'tot':tot})
        
    else:
        return redirect('login')

# Email ------------------

def EmailCall(request,id):
    if 'org' in request.session:
        org = OrganisationDetails.objects.get(user_id = request.session['org'])
        invo = Invoice_Details.objects.get(id=id)
        prod = Product.objects.filter(Invoice=invo)
        cust_data = CustomerDetails.objects.get(cust_name=invo.Cust_name)
        tot = 0
        for i in prod:
            tot += float(i.Total)
        data = {'org':org,'cust':cust_data,'invo':invo,'prod':prod,'tot':tot}
        
        
        # my_email = "darpansalunkework@gmail.com"
        # my_pass = "darpan@work"
        # fr_email = "darpansalunke@gmail.com"
        try:
            my_email = org.email
            my_pass = org.password_2
            fr_email = cust_data.email
            
            server = smtplib.SMTP('smtp.gmail.com',587)
            
            mead_data =""
                
            front = """
            <!DOCTYPE html>
            <html>
                <body>
                    <div>
                        <h2>Company Name : """ + org.company_name + """</h2>
                        <h2>Customer Name : """ + cust_data.cust_name + """</h2>
                        <h2>Invoice No. : """ + invo.Invoice_num + """</h2>
                    </div>
                    <br>
                    <div>
                        <table border="2">
                            <thead>
                                <tr>
                                    <th>
                                        Product Name
                                    </th>
                                    <th>
                                        Hsn Code
                                    </th>
                                    <th>
                                        Qty
                                    </th>
                                    <th>
                                        Price
                                    </th>
                                    <th>
                                        Discount
                                    </th>
                                    <th>
                                        Cgst
                                    </th>
                                    <th>
                                        Sgst
                                    </th>
                                    <th>
                                        Igst
                                    </th>
                                    <th>
                                        Cess
                                    </th>
                                    <th>
                                        Total
                                    </th>
                                </tr>
                            </thead>
                            <tbody>"""
                            
            for i in prod:
                mead_data += """<tr>
                <td>""" + str(i.Product_name) + """ </td>
                <td>""" + str(i.Hsn_code) + """ </td> 
                <td>""" + str(i.Qty) + """</td>
                <td>""" + str(i.Price) + """</td>
                <td>""" + str(i.Discount) + """</td>
                <td>""" + str(i.Cgst) + """</td>
                <td>""" + str(i.Sgst) + """</td>
                <td>""" + str(i.Igst) + """</td>
                <td>""" + str(i.Cess) + """</td>
                <td>""" + str(i.Total) + """</td>
                </tr> """
                
            ended = f"""
            </tbody> </table> </body> </html>
            <h2> Amount To Pay : {tot} <h2>"""
            
            email_content = front + mead_data + ended
            print(email_content)
            
            msg = email.message.Message()
            msg['Subject'] = f'Your Invoice No. {invo.Invoice_num} From {org.company_name}' 
            msg['From'] = my_email
            msg['To'] = fr_email
            password = my_pass
            msg.add_header('Content-Type', 'text/html')
            msg.set_payload(email_content)
            s = smtplib.SMTP('smtp.gmail.com',587)
            s.starttls()
            s.login(msg['From'], password)
            s.sendmail(msg['From'], [msg['To']], msg.as_string())
        
            # return HttpResponse("<h1>Email Sent<h2>")
            data1 = "Email Sent"
            return render(request,'Error_Show.html',{'data1':data1})
        except:
            data1 = "Email Not Sent"
            data2 = "Maybe Your Email Id Or Password Is Wrong"
            return render(request,'Error_Show.html',{'data1':data1,'data2':data2})
            
    else:
        return redirect('login')

# Organisation -------------

def OrganisationView(request):
    forms = OrganisationForm(request.POST or None)
    if request.POST:
        if forms.is_valid():
            try:
                valid = OrganisationDetails.objects.get(user_id=request.POST['user_id'])
                return HttpResponse("<h2><a href=''>User Id Already In Use </a></h2>")
            except:
                forms.save()
                request.session['org'] = request.POST['user_id']
                return redirect('login')
        else:
            print('not valid')
    else:
        print('not post')
    return render(request,'signup.html',{'org':forms})

def LoginView(request):
    if request.method == "POST":
        try:
            m = OrganisationDetails.objects.get(user_id = request.POST['username'])
            if m.password_2 == request.POST['password']:
                print(m.user_id)
                request.session['org'] = m.user_id
                request.session['orgid'] = m.pk
                return redirect('index')
            else:
                return HttpResponse("<h2><a href=''>You have entered wrong password</a></h2>")
        except:
            return HttpResponse("<h2><a href=''>no username found.</a></h2>")
    return render(request,'registration/login.html')

# Forget Password -----------------

def forgot_pass(request):
    if request.POST:
        email1 = request.POST['email']
        number1 = request.POST['m_no']
            
        try:
            valid = OrganisationDetails.objects.get(email=email1)

Biling 21.04.2023/organisation/templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'OpenSans.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fieldset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'footable.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'jquery-te-1.4.0.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'jquery-ui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'multi-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plans.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'my-bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-responsive.min.css' %}">

    <style>
        ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
        }
        
        li {
          float: left;
        }
        
        
        li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
        }
        
        li a:hover:not(.active) {
          background-color: #111;
        }
        
        .active {
          background-color: red;
        }
        .ret{
            display: block;
          color: white;
          text-align: center;
          font-size: 20px;
          padding: 14px 16px;
          text-decoration: none;
            
        }
        .divpad{
            padding: 14px 16px;
        }
        </style>
    </head>
    <body>
        <ul>
            <li class = "ret">Advance Billing System</li>
            <li><a href="{% url 'index' %}" >Dashboard</a></li>
            <li><a href="{% url 'customer' %}">Customer</a></li>
            <li><a href="{% url 'invoiceview' %}">Sale Invoice</a></li>
            <li><a href="{% url 'addProductForm' %}">Add Product</a></li>
            <li><a href="{% url 'viewquentity' %}">View Product</a></li>
            <li style="float:right"><a class="active" href="{% url 'logout' %}">Logout</a></li>
            <li style="float:right" class="ret">{{org}}</li>
          </ul>

<br><br><br>
    {% block content %}
    {% endblock %}

 
</body>
</html>

Biling 21.04.2023/organisation/templates/customerform.html
{% extends 'base.html' %}

{% block content %}

<div class="main">
    <div class="main-inner">	
        <div class="container">
        <div class="row">
            <div class="span12">
                <center>
        
                                            <!-- gst header after login -->
                        <ins class="adsbygoogle" style="display: inline-block; width: 728px; height: 0px;" data-ad-client="ca-pub-7485845865785659" data-ad-slot="9888667777" data-adsbygoogle-status="done"><ins id="aswift_0_expand" style="display: inline-table; border: none; height: 0px; margin: 0px; padding: 0px; position: relative; visibility: visible; width: 728px; background-color: transparent;"><ins id="aswift_0_anchor" style="display: block; border: none; height: 0px; margin: 0px; padding: 0px; position: relative; visibility: visible; width: 728px; background-color: transparent; overflow: hidden; opacity: 0;"><iframe width="728" height="90" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no" allowfullscreen="true" onload="var i=this.id,s=window.google_iframe_oncopy,H=s&amp;&amp;s.handlers,h=H&amp;&amp;H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&amp;&amp;d&amp;&amp;(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}" id="aswift_0" name="aswift_0" style="left:0;position:absolute;top:0;border:0px;width:728px;height:90px;"></iframe></ins></ins></ins>
                        <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                                    </center>
            </div>
        </div>
    </div>	
        <div class="container">
        
                    <div class="row">
                <div class="span12">
                                    <div class="widget">
                        <div class="widget-header"> <i class="fa fa-pencil"></i>
                            <h3>Add Customer / Vendor</h3>
                        </div>
                        <div class="widget-content">
                            <form class="form-horizontal" method="POST">
                                {% csrf_token %}
                                <fieldset>
                                
                                <div class="main-row"><div class="left-col">
                                    <!--------------- -------------------------------------------------->

                                    <div class="control-group">											
                                        <label for="Customer / Vendor Name" class="control-label">Customer / Vendor Name *</label>
                                        <div class="controls">
                                            <input type="text" name="cust_name" id="id_cust_name" value="{{data.cust_name}}">
                                        </div> <!-- /controls -->	
                                    </div> <!-- /control-group -->
                                    
                                    <div class="control-group">											
                                        <label for="Contact Person" class="control-label">Contact Person *</label>
                                        <div class="controls">
                                            <input type="text" name="cont_person" id="id_cont_person" value="{{ data.cont_person }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    
                                    <div class="control-group">											
                                        <label for="Contact No" class="control-label">Contact No *</label>
                                        <div class="controls">
                                            <input type="number" name="contact_num" id="id_contact_num" value="{{ data.contact_num }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                        
                                    <div class="control-group">											
                                        <label for="Contact No" class="control-label">Email *</label>
                                        <div class="controls">
                                            <input type="text" name="email" id="id_email" value="{{ data.email }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->

                                    <div class="control-group">											
                                        <label for="Contact No" class="control-label">Company Type *</label>
                                        <div class="controls">
                                            <input type="text" name="company_type" id="id_company_type" value="{{ data.company_type }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->

            
                                    <div class="control-group">											
                                        <label for="Address" class="control-label">Address 1 *</label>
                                        <div class="controls">
                                       <input type="text" name="address" id="id_address" value="{{data.address}}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    
                                    <div class="control-group">		
                                        <label for="Address" class="control-label">Address 2 *</label>
                                        <div class="controls">
                                       <input type="text" name="address_2" id="id_address_2" value="{{data.address_2}}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    
                                    <div class="control-group">											
                                        <label for="LandMark" class="control-label">LandMark *</label>
                                        <div class="controls">
                                            <input type="text" name="landmark" id="id_landmark" value="{{ data.landmark }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    <div class="control-group">
                                        <label for="Country" class="control-label">Country *</label>
                                        <div class="controls">
                                        <input type="text" name="country" id="id_country" value="{{ data.country }}">
                                        </div> <!-- /controls -->
                                    </div> <!-- /control-group -->									
                                    <div class="control-group">											
                                        <label for="State" class="control-label">State *</label>
                                        <div class="controls">
                                        <input type="text" name="state" id="id_state" value="{{ data.state }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    
                                    <div class="control-group">											
                                        <label for="City" class="control-label">City *</label>
                                        <div class="controls">
                                            <input type="text" name="city" id="id_city" value="{{ data.city }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->	
                                    
                                   
                                    
                                    <div class="control-group hide" id="Vender-detail1">																					<label for="Bank Name" class="control-label">Bank Name</label>										<div class="controls">																						<input type="text" value="" name="bankname" id="bankname" placeholder="Enter bank name" class="span4" maxlength="50">										</div> <!-- /controls -->													</div> <!-- /control-group -->																		<div class="control-group hide" id="Vender-detail2">																					<label for="IFSC Code" class="control-label">Bank IFSC Code</label>										<div class="controls">																						<input type="text" value="" name="ifsccode" id="ifsccode" placeholder="Enter IFSC code" class="span4" maxlength="50">										</div> <!-- /controls -->													</div> <!-- /control-group -->																		<div class="control-group hide" id="Vender-detail3">																					<label for="Account Number" class="control-label">Bank Account Number</label>										<div class="controls">																						<input type="text" value="" name="accountno" id="accountno" placeholder="Enter account number" class="span4" maxlength="50">										</div> <!-- /controls -->													</div> <!-- /control-group -->								
                                    <div class="control-group">											
                                        <label for="Pincode" class="control-label">Pincode</label>
                                        <div class="controls">
                                        <input type="number" name="pincode" id="id_pincode" value="{{ data.pincode }}">
                                        </div> <!-- /controls -->				
                                    </div> <!-- /control-group -->
                                    
                                   
                                    
                                    </div>
                                    </div>
                                    <div class="form-actions">
                                        
                                        <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i>Save</button> 
                                    </div> <!-- /form-actions -->
                                        
                                    <!--------------- -------------------------------------------------->
                                    
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div> 
            </div>
    

</div> </div> </div>	
{% endblock %}